spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lsy200304144815
    url: jdbc:mysql://localhost:3306/big_event
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 设置上传文件的最大大小，默认为 1MB
      max-request-size: 100MB  # 设置请求中最大允许的文件大小，默认为 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
    log-impl=org:
      apache:
        ibatis:
          logging:
            stdout:
              StdOutImpl:
